module.exports = {
    FETCH_USERS: 'FETCH_USERS',
    REMOVE_USERS: 'REMOVE_USERS',
    SEARCH_USER: 'SEARCH_USER',
    ASSIGN_USERS_TO_FILTERED: 'ASSIGN_USERS_TO_FILTERED',
    NATIONALITIES: 'NATIONALITIES',
    LOADING: 'LOADING'
}